FROM python:3.10-slim
WORKDIR /app
COPY fastapi_services/requirements.txt .
RUN pip install -r requirements.txt
COPY fastapi_services/rag_worker/ ./rag_worker/
COPY fastapi_services/key_manager.py .
CMD uvicorn rag_worker.main:app --host 0.0.0.0 --port $PORT
