FROM python:3.10-slim
RUN apt-get update && apt-get install -y ffmpeg yt-dlp
WORKDIR /app
COPY youtube_app/requirements.txt .
RUN pip install -r requirements.txt
COPY youtube_app/ .
CMD uvicorn main:app --host 0.0.0.0 --port $PORT
