FROM python:3.10-slim
WORKDIR /app
COPY fastapi_services/requirements.txt .
RUN pip install -r requirements.txt
COPY fastapi_services/sentiment/ ./sentiment/
COPY fastapi_services/key_manager.py .
CMD uvicorn sentiment.main:app --host 0.0.0.0 --port $PORT
