[supervisord]
nodaemon=true
user=root

[program:django]
command=gunicorn --chdir /app/django_app config.wsgi:application --bind 0.0.0.0:7860 --workers 2 --timeout 120
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:youtube_service]
command=uvicorn youtube_app.main:app --host 0.0.0.0 --port 8005
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:sentiment_service]
command=uvicorn fastapi_services.sentiment.main:app --host 0.0.0.0 --port 8010
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:rag_worker]
command=uvicorn fastapi_services.rag_worker.main:app --host 0.0.0.0 --port 8011
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
